/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab7;

import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class AddNewCD extends javax.swing.JFrame {

    /**
     * Creates new form AddNewCD
     */
    public AddNewCD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cdId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cdTitle = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        collectionCD = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        vcd = new javax.swing.JRadioButton();
        CD = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cdPrice = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cdYear = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusTraversalPolicyProvider(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(7, 1));

        jLabel1.setText("CD ID");
        jPanel1.add(jLabel1);

        cdId.setMinimumSize(new java.awt.Dimension(400, 25));
        cdId.setPreferredSize(new java.awt.Dimension(400, 25));
        cdId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdIdActionPerformed(evt);
            }
        });
        jPanel1.add(cdId);

        getContentPane().add(jPanel1);

        jLabel2.setText("CD Title");
        jPanel2.add(jLabel2);

        cdTitle.setMinimumSize(new java.awt.Dimension(400, 25));
        cdTitle.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel2.add(cdTitle);

        getContentPane().add(jPanel2);

        jLabel3.setText("CD Collection");
        jPanel3.add(jLabel3);

        collectionCD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie", "Game", "Music" }));
        jPanel3.add(collectionCD);

        jLabel4.setText("CD Type");
        jPanel3.add(jLabel4);

        buttonGroup1.add(vcd);
        vcd.setText("VCD");
        vcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcdActionPerformed(evt);
            }
        });
        jPanel3.add(vcd);

        buttonGroup1.add(CD);
        CD.setText("CD");
        jPanel3.add(CD);

        getContentPane().add(jPanel3);

        jLabel5.setText("CD Price");
        jPanel4.add(jLabel5);

        cdPrice.setMinimumSize(new java.awt.Dimension(400, 25));
        cdPrice.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel4.add(cdPrice);

        getContentPane().add(jPanel4);

        jLabel6.setText("CD year of release");
        jPanel5.add(jLabel6);

        getContentPane().add(jPanel5);

        cdYear.setMinimumSize(new java.awt.Dimension(400, 25));
        cdYear.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel6.add(cdYear);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        getContentPane().add(jPanel6);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        jButton3.setText("Show All");
        jPanel7.add(jButton3);

        getContentPane().add(jPanel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdIdActionPerformed

    private void vcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcdActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String CDid = cdId.getText();
            String CDtitle = cdTitle.getText();
            String CDCollection = collectionCD.getSelectedItem().toString();
            String CDtype = vcd.isSelected()==true?"VCD":"CD";
            int price = Integer.parseInt(cdPrice.getText());
            int year = Integer.parseInt(cdYear.getText());
            CD newCd = new CD(CDid,CDCollection,CDtype,CDtitle,price,year);
            if(newCd.addCD(newCd)){
                JOptionPane.showMessageDialog(null, "Success", "Message", JOptionPane.INFORMATION_MESSAGE);
            }else JOptionPane.showMessageDialog(null, "False", "Message", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            cdId.setText("");
            cdTitle.setText("");
            cdPrice.setText("");
            cdYear.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewCD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CD;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cdId;
    private javax.swing.JTextField cdPrice;
    private javax.swing.JTextField cdTitle;
    private javax.swing.JTextField cdYear;
    private javax.swing.JComboBox<String> collectionCD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton vcd;
    // End of variables declaration//GEN-END:variables
}
